CREATE TABLE MESMGR.TKG_THR_WHEEL
(
  ID             CHAR(10 BYTE),
  ISLOSER        NUMBER,
  IP_ADDR        CHAR(14 BYTE),
  CREATION_DATE  DATE,
  UPDATE_DATE    DATE,
  SPIN           NUMBER,
  SALDO          NUMBER
)